void vsync();
void set_color(char c, unsigned char r, unsigned char g, unsigned char b);
void init_color();

#define COLOR_BLACK 0
#define COLOR_WHITE 1
#define COLOR_BLUE 2
#define COLOR_RED 3
#define COLOR_YELLOW 4
#define COLOR_DARKBLUE 5
#define COLOR_GREEN 6
#define COLOR_GREY 7

// Aliases for colors of objects
#define COLOR_QUADRO COLOR_BLUE
#define COLOR_SEVIL COLOR_RED
#define COLOR_KEVIL COLOR_YELLOW
#define COLOR_WALL COLOR_GREY

